### ISSUE TITLE
[REQ] Add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [AakashRevankar/Auto_regressive_filter#1]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO section](https://github.com/FORARTfe/HyMPS#- ) \ [AI-based category](https://github.com/FORARTfe/HyMPS/blob/main/Audio/AI-based.md#-- ) \ [Enhancers page](https://github.com/FORARTfe/HyMPS/blob/main/Audio/AI-Enhancing.md#--- ) \ [Restorers](https://github.com/FORARTfe/HyMPS/blob/main/Audio/AI-Enhancing.md#restorers-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/AakashRevankar/Audio_restoration_using_auto_regressive_filter)
(badge-generator URL: https://badgen.net/github/license/AakashRevankar/Audio_restoration_using_auto_regressive_filter)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by MarcoRavich** [comment]
Bump (request updated).

**Comment by AakashRevankar** [comment]
Hello Marco,

Thank you for reaching out. I gave a glimpse to "HPS project" and I am grateful that my project is a part of it. As of now, I have added "GNU general public license 3.0". 

I am willing to contribute to your non-profit art organization "forart" and I am looking forward to hear from you.
Please let me know if the issue is resolved.

**Comment by MarcoRavich** [comment]
Thanks a lot, as you can see it works now (collection page updated too).

I'm partecipating to a [discussion @ OpenVINO™ AI Plugins for Audacity](https://github.com/intel/openvino-plugins-ai-audacity/discussions/278) on audio upscalers/enhancers that is getting very interesting... many users - like me - are newbies, so it would be really useful to have some expert developers - like you - intervene.

Thanks again.
